name: healthymeal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.0
  image_picker: ^1.0.4
  intl: ^0.20.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    #현재 미사용 - assets/files/
    - assets/image/
  fonts:
    - family: korfont1
      fonts:
        - asset: assets/fonts/Jua-Regular.ttf



