name: healthymeal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # ✅ DatePicker 로케일 지원용
    sdk: flutter
  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.0
  image_picker: ^1.0.4
  intl: 0.19.0
  http: ^1.1.0
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/chicken.jpg
    - assets/images/
    - assets/icons/

  fonts:
    - family: korfont1
      fonts:
        - asset: assets/fonts/Jua-Regular.ttf
